"""Unit tests for the pure sigrok-cli output parsers. No binary, no hardware."""

from __future__ import annotations

from boardex_logic import parse

SCAN = """\
The following devices were found:
kingst-la2016:conn=3.7 - Kingst LA2016 with 16 channels: D0 D1 D2 D3 D4 D5 D6 D7 D8 D9 D10 D11 D12 D13 D14 D15
fx2lafw:conn=1.24 - Saleae Logic with 8 channels: D0 D1 D2 D3 D4 D5 D6 D7
"""

SHOW = """\
Driver functions:
    Logic analyzer
    Continuous sampling
kingst-la2016:conn=3.7 - Kingst LA2016 with 16 channels: D0 D1 D2 D3 D4 D5 D6 D7 D8 D9 D10 D11 D12 D13 D14 D15
Supported configuration options across all logical channel groups:
    Trigger matches: 0 1 r f
Supported configuration options:
    Sample rate - supported samplerates:
      20 kHz
      50 kHz
      1 MHz
      100 MHz
      200 MHz
"""

CSV = """\
D0,D1,D2
0,1,0
0,1,0
1,1,0
1,0,0
"""


def test_parse_rate_units():
    assert parse.parse_rate("20 kHz") == 20_000
    assert parse.parse_rate("100 MHz") == 100_000_000
    assert parse.parse_rate("1.5 GHz") == 1_500_000_000
    assert parse.parse_rate("nope") is None


def test_parse_scan():
    devices = parse.parse_scan(SCAN)
    assert [d.driver for d in devices] == ["kingst-la2016", "fx2lafw"]
    kingst = devices[0]
    assert kingst.spec == "kingst-la2016:conn=3.7"
    assert kingst.conn == "3.7"
    assert kingst.model == "Kingst LA2016"
    assert len(kingst.channels) == 16


def test_parse_show():
    caps = parse.parse_show(SHOW)
    assert len(caps["channels"]) == 16
    assert caps["max_sample_rate_hz"] == 200_000_000
    assert 20_000 in caps["samplerates"]
    assert caps["triggers"] == ["low", "high", "rising", "falling"]


def test_parse_csv_transitions():
    result = parse.parse_csv(CSV)
    assert result["num_samples"] == 4
    assert result["channels"] == ["D0", "D1", "D2"]
    assert result["transitions"]["D0"] == [[0, 0], [2, 1]]
    assert result["transitions"]["D1"] == [[0, 1], [3, 0]]
    assert result["transitions"]["D2"] == [[0, 0]]


def test_parse_csv_drops_time_column():
    csv = "time,D0\n0.0,0\n0.1,1\n"
    result = parse.parse_csv(csv)
    assert result["channels"] == ["D0"]
    assert result["transitions"]["D0"] == [[0, 0], [1, 1]]


def test_parse_csv_libsigrok_format():
    # Real libsigrok 0.5.2 output: comment block with channel names, then rows.
    csv = (
        "; CSV generated by libsigrok 0.5.2\n"
        "; Channels (2/13): D0, D1\n"
        "; Samplerate: 1 MHz\n"
        "logic,logic\n"
        "1,0\n"
        "0,0\n"
        "0,1\n"
    )
    result = parse.parse_csv(csv)
    assert result["channels"] == ["D0", "D1"]
    assert result["num_samples"] == 3
    assert result["transitions"]["D0"] == [[0, 1], [1, 0]]
    assert result["transitions"]["D1"] == [[0, 0], [2, 1]]


def test_parse_annotations():
    text = "0-1200 i2c: START\n1200-4000 i2c: ADDRESS WRITE: 48\n"
    ann = parse.parse_annotations(text)
    assert ann[0]["start"] == 0
    assert ann[0]["decoder"] == "i2c"
    assert ann[1]["text"] == "ADDRESS WRITE: 48"
