import js from '@eslint/js';
import tseslint from 'typescript-eslint';
import globals from 'globals';
import reactHooks from 'eslint-plugin-react-hooks';
import reactRefresh from 'eslint-plugin-react-refresh';

// Minimal flat config. servers/ (Python) and examples/ (firmware) are the backend
// owner's domain and are never linted; build artifacts and generated files are ignored.
export default tseslint.config(
  {
    ignores: [
      '**/dist/**',
      '**/coverage/**',
      '**/node_modules/**',
      '**/*.config.js',
      '**/*.config.ts',
      'servers/**',
      'examples/**',
      // Python virtualenv (backend-land): vendored JS inside pip must not lint.
      '.venv/**',
      'packages/contract/json-schema/**',
      'packages/contract/fixtures/**',
      // Demo-video shoot scripts (chore/demo-video): Playwright ESM driving the UI
      // for a walkthrough recording. Not part of the shipped product; not a workspace.
      'tools/demo-video/**',
      // Generated by the `boardex` distribution's build hook — a copy of the
      // BUILT UI (minified bundles) that ships inside the wheel, never source.
      'boardex-app/boardex_app/_bundled/**',
    ],
  },
  js.configs.recommended,
  ...tseslint.configs.recommended,
  {
    files: ['apps/ui/**/*.{ts,tsx}'],
    plugins: {
      'react-hooks': reactHooks,
      'react-refresh': reactRefresh,
    },
    languageOptions: {
      globals: { ...globals.browser },
    },
    rules: {
      'react-hooks/rules-of-hooks': 'error',
      'react-hooks/exhaustive-deps': 'warn',
      'react-refresh/only-export-components': ['warn', { allowConstantExport: true }],
    },
  },
  {
    files: ['tools/mock-runner/**/*.ts'],
    languageOptions: {
      globals: { ...globals.node },
    },
  },
);
